version: '3.9'
services:
  umami:
    image: ghcr.io/mikecao/umami:mysql-latest
    hostname: "umami"
    container_name: "umami"
    environment:
      DATABASE_URL: mysql://USERNAME:PASSWORD@mysql:3306/umami
      HASH_SALT: "YOUR SALT"
    restart: always
    networks:
      - app
networks:
  app:
    external: true

