version: '3.9'
services:
  umami:
    image: pabloszx/umami
    hostname: "umami"
    container_name: "umami"
    environment:
      DATABASE_URL: "mysql://umami:umami#2022@mysql:3306/umami"
      HASH_SALT: "flyingcrp"
    restart: always
    networks:
      - app
networks:
  app:
    external: true

