version: '3.9'
services:
  portainer:
    image: 'portainer/portainer-ce:latest'
    restart: "unless-stopped"
    hostname: "portainer"
    container_name: "portainer"
    networks:
      - app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/workspace/volume_datas/portainer_data:/data
    ports:
      - "8000:8000"
      - "9443:9443"
networks:
  app:
    external: true