version: '3.9'
services:
  redis:
    image: 'bitnami/redis:latest'
    restart: "unless-stopped"
    hostname: "redis"
    container_name: "redis"
    networks:
      - app
    volumes:
      - /root/workspace/volume_datas/redis/data:/bitnami/redis/data
    environment:
      - REDIS_PASSWORD=YOUR-PASSWORD
      - REDIS_PORT_NUMBER=YOUR-PORT
networks:
  app:
    external: true